language: java
jdk:
  - oraclejdk8
# Override the default installer; we don't want `mvn install` to run.
install: true
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
